FROM docker.io/library/debian@sha256:82f8da149d6d567c74564cccd6f355fb5ade42a958e4cde10a1100eaeb24d42e

ARG DEBIAN_FRONTEND=noninteractive
ARG TERM=linux
ARG OSM_3S_VERSION=0.7.62

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
    bzip2 \
    ca-certificates \
    expat \
    fcgiwrap \
    g++ \
    gzip \
    less \
    libexpat1-dev \
    libnss-systemd \
    make \
    nano \
    nginx \
    systemd \
    systemd-container \
    wget \
    zlib1g-dev && \
    rm -rf /var/lib/apt/lists/*

# create db user
RUN useradd -m -U -s /bin/bash osm_user

# install osm-3s
RUN cd /home/osm_user && \
    wget http://dev.overpass-api.de/releases/osm-3s_v$OSM_3S_VERSION.tar.gz && \
    tar -zxvf osm-3s_v$OSM_3S_VERSION.tar.gz && \
    cd osm-3s_v$OSM_3S_VERSION && \
    ./configure CXXFLAGS="-O2" && \
    make install
RUN cd /home/osm_user && \
    mv osm-3s_v$OSM_3S_VERSION osm-3s && \
    chown -R osm_user:osm_user osm-3s && \
    chmod u+x osm-3s/bin/*.sh

# set interval for area updates
RUN sed -i -e 's/sleep 3/sleep 3600/g' /usr/local/bin/rules_loop.sh
    
# copy boot scripts and systemd services
COPY ./assets/boot.sh /opt/boot.sh
RUN chmod 700 /opt/boot.sh
COPY ./assets/boot_script.service /etc/systemd/system/boot_script.service
RUN systemctl enable boot_script.service
COPY ./assets/dispatcher_base.service /etc/systemd/system/dispatcher_base.service
RUN systemctl enable dispatcher_base.service
RUN mkdir /opt/osm_diffs && \
    chown osm_user:osm_user /opt/osm_diffs
COPY ./assets/fetch_diff.service /etc/systemd/system/fetch_diff.service
RUN systemctl enable fetch_diff.service
COPY ./assets/apply_diff.service /etc/systemd/system/apply_diff.service
RUN systemctl enable apply_diff.service
COPY ./assets/dispatcher_areas.service /etc/systemd/system/dispatcher_areas.service
RUN systemctl enable dispatcher_areas.service
COPY ./assets/areas.service /etc/systemd/system/areas.service
RUN systemctl enable areas.service

# setup nginx
COPY ./assets/nginx_default /etc/nginx/sites-available/default
RUN systemctl enable fcgiwrap

# disable root login (should be disabled by default, just to be sure...)
RUN passwd -l root

    
WORKDIR /

EXPOSE 8000

ENTRYPOINT ["/lib/systemd/systemd"]
